# removed as test_demo depends on too many dependencies
os: linux
dist: focal
language: perl
perl:
  - "5.28"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y wget python3 python3-pip python3-setuptools mysql-client libmysqlclient-dev g++-10 bedtools r-base"

# https://travis-ci.community/t/accessing-old-versions-of-perl-in-a-c-language-build/10948/5
install: skip 

before_script:
  - "make install_REST"
  - "make install_ensembl"
  - "make install_repeats"
  - PERL5LIB=$PWD/lib:$PERL5LIB
  - export PERL5LIB

script:
  - "make test_travis"
  - "make test_repeats_travis"

notifications:
  email:
    on_failure: always
